services:
  dev:
    build:
      context: .
      dockerfile: docker/Dockerfile
      args:
        USER_UID: ${UID:-1000}
        USER_GID: ${GID:-1000}
        USERNAME: tomasdea
    image: tesis-ros2:humble-cpu
    container_name: tesis_nav_dev
    network_mode: host
    ipc: host
    privileged: true

    devices:
      - "/dev/ttyACM0:/dev/ttyACM0"
      - "/dev/bus/usb:/dev/bus/usb"
      - "/dev/video0:/dev/video0"
      - "/dev/video1:/dev/video1"
      - "/dev/video2:/dev/video2"
      - "/dev/video3:/dev/video3"
      - "/dev/video4:/dev/video4"
      - "/dev/video5:/dev/video5"
      - "/dev/video6:/dev/video6"
      - "/dev/video7:/dev/video7"

    group_add:
      - "dialout"
      - "video"
      - "plugdev"

    environment:
      - DISPLAY=${DISPLAY}
      - ROS_DISTRO=humble
      - RUNNING_IN_CONTAINER=1
      - BASH_ENV=/etc/profile.d/context.sh
      - WS_PATH=${CONTAINER_WS}

    volumes:
      - ${HOST_WS}:${CONTAINER_WS}
      - /tmp/.X11-unix:/tmp/.X11-unix
      - ./docker/context.sh:/etc/profile.d/context.sh:ro

    working_dir: ${CONTAINER_WS}
    tty: true
