<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>nav_bringup</name>
  <version>0.0.1</version>
  <description>Bringup launch files for the complete navigation pipeline.</description>
  <maintainer email="dev@todo.todo">dev</maintainer>
  <license>TODO: License declaration</license>

  <depend>launch</depend>
  <depend>launch_ros</depend>
  <depend>ament_index_python</depend>

  <exec_depend>realsense2_camera</exec_depend>
  <exec_depend>local_mapper</exec_depend>
  <exec_depend>depth_grid_encoder</exec_depend>
  <exec_depend>haptic_grid_generator</exec_depend>
  <exec_depend>hardware_manager</exec_depend>
  <exec_depend>output_viewer</exec_depend>

  <test_depend>ament_copyright</test_depend>
  <test_depend>ament_flake8</test_depend>
  <test_depend>ament_pep257</test_depend>
  <test_depend>python3-pytest</test_depend>

  <export>
    <build_type>ament_python</build_type>
  </export>
</package>
