depth_to_matrix:
  ros__parameters:
    depth_topic: "/camera/camera/depth/image_rect_raw"
    rows: 5
    cols: 10
    z_min_m: 0.25
    z_max_m: 2.0
    #metric: "min"        
    #smoothing_alpha: 0.0   

